# Generated by Django 3.2.14 on 2022-09-22 06:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institute_id', models.CharField(max_length=100)),
                ('createdBy_id', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institute_id', models.CharField(max_length=100)),
                ('createdBy_id', models.CharField(max_length=100)),
                ('extra_venue_name', models.CharField(blank=True, max_length=40, null=True)),
                ('trainer', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode_of_delivery', models.IntegerField(choices=[(0, 'Physical'), (1, 'Online')], default=0, verbose_name='Mode  of Delivery')),
                ('description', models.TextField(max_length=30)),
                ('theme', models.CharField(max_length=255)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('topic', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('participant_limit', models.PositiveIntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'UpComing'), (1, 'OnGoing'), (2, 'Cancelled'), (3, 'Postponed')], default=0, verbose_name='Status')),
                ('slots_remaining', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institute_id', models.CharField(max_length=100)),
                ('createdBy_id', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-capacity'],
            },
        ),
        migrations.CreateModel(
            name='TrainingApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institute_id', models.CharField(max_length=100)),
                ('createdBy_id', models.CharField(max_length=100)),
                ('train_appller', models.CharField(blank=True, max_length=255, null=True)),
                ('request_type', models.IntegerField(choices=[(0, 'Pool'), (1, 'Individual')], default=0, verbose_name='Request_Type')),
                ('participant_no', models.PositiveIntegerField(default=0)),
                ('status_feedback', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved with changes'), (2, 'Approved'), (3, 'Rejected')], default=0, verbose_name='Feedback Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.training')),
            ],
            options={
                'ordering': ['-status_feedback'],
            },
        ),
        migrations.AddField(
            model_name='training',
            name='venue_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='training.venue'),
        ),
        migrations.CreateModel(
            name='AudienceCategoryTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audienceCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='training.audiencecategory')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='training.training')),
            ],
            options={
                'unique_together': {('training', 'audienceCategory')},
            },
        ),
    ]
