
federation_version: 2
subgraphs:
  uaa_service:
    routing_url: http://0.0.0.0:8080/graphql
    schema:
      subgraph_url: http://0.0.0.0:8080/graphql
  training_service:
    routing_url: http://0.0.0.0:8082/graphql
    schema:
      subgraph_url: http://0.0.0.0:8082/graphql
